# Generated by Django 5.2.3 on 2026-04-17 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('add', 'إضافة مخزون'), ('adjust', 'تعديل'), ('reserve', 'حجز (طلب جديد)'), ('sold', 'مبيع (تم التسليم)'), ('release', 'إلغاء الحجز')], db_index=True, max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive = incoming, Negative = outgoing', max_digits=12, verbose_name='الكمية')),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية قبل')),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية بعد')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='ملاحظة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.product', verbose_name='المنتج')),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order', verbose_name='الطلب المرتبط')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='inventory_i_product_d7930e_idx'), models.Index(fields=['movement_type', '-created_at'], name='inventory_i_movemen_979428_idx')],
            },
        ),
    ]
