# Generated by Django 5.2.3 on 2026-04-17 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unassigned', 'غير مكلف'), ('assigned', 'مكلف'), ('picked_up', 'تم الاستلام من المزارع'), ('delivered', 'تم التسليم'), ('failed', 'فشل التسليم')], default='unassigned', max_length=20, verbose_name='الحالة')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستلام')),
                ('delivered_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='السائق')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مهمة توصيل',
                'verbose_name_plural': 'مهام التوصيل',
                'ordering': ['-created_at'],
            },
        ),
    ]
