# Generated by Django 5.2.3 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryassignment",
            name="delivery_mode",
            field=models.CharField(
                choices=[("driver", "سائق من النظام"), ("self_delivery", "توصيل ذاتي من المزرعة")],
                default="driver",
                max_length=20,
                verbose_name="طريقة التسليم",
            ),
        ),
    ]
