# Generated by Django 5.2.3 on 2026-04-17 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الحالي')),
                ('farmer', models.OneToOneField(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='المزارع')),
            ],
            options={
                'verbose_name': 'محفظة',
                'verbose_name_plural': 'المحافظ',
            },
        ),
        migrations.CreateModel(
            name='WalletLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('credit', 'إيداع (مبيعات)'), ('debit', 'خصم'), ('hold', 'تجميد مؤقت'), ('release', 'إلغاء تجميد'), ('settlement', 'تسوية مالية')], db_index=True, max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الرصيد قبل')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الرصيد بعد')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='الوصف')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallets.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'حركة المحفظة',
                'verbose_name_plural': 'حركات المحافظ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallets_wal_wallet__26c32b_idx'), models.Index(fields=['entry_type', '-created_at'], name='wallets_wal_entry_t_7a96b6_idx'), models.Index(fields=['reference_type', 'reference_id'], name='wallets_wal_referen_2613f7_idx')],
            },
        ),
    ]
