# Generated by Django 5.2.3 on 2026-04-17 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المزرعة')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='القرية')),
                ('address', models.TextField(blank=True, verbose_name='العنوان التفصيلي')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة عن المزرعة')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='farmers/avatars/', verbose_name='الصورة الشخصية')),
                ('preferred_payout_method', models.CharField(choices=[('cash', 'نقداً'), ('bank', 'تحويل بنكي'), ('wallet', 'محفظة إلكترونية')], default='cash', max_length=20, verbose_name='طريقة الصرف المفضلة')),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المزارع',
                'verbose_name_plural': 'ملفات المزارعين',
            },
        ),
    ]
