# Generated by Django 5.2.3 on 2026-04-17 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=200, unique=True, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/', verbose_name='الصورة')),
                ('audio_file', models.FileField(blank=True, help_text='Voice description - will be transcribed via Whisper', null=True, upload_to='products/audio/%Y/%m/', verbose_name='الملف الصوتي')),
                ('transcription_text', models.TextField(blank=True, null=True, verbose_name='النص المستخرج من الصوت')),
                ('transcription_status', models.CharField(choices=[('none', 'لا يوجد'), ('pending', 'قيد المعالجة'), ('processing', 'يتم المعالجة'), ('done', 'مكتمل'), ('failed', 'فشل')], default='none', max_length=20, verbose_name='حالة الاستخراج')),
                ('quantity_available', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='الكمية المتاحة')),
                ('unit', models.CharField(choices=[('kg', 'كيلوغرام'), ('gram', 'غرام'), ('ton', 'طن'), ('box', 'صندوق'), ('bunch', 'ربطة'), ('piece', 'حبة'), ('liter', 'لتر'), ('bag', 'كيس')], default='kg', max_length=20, verbose_name='الوحدة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('harvest_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحصاد')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='مميز')),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='حد المخزون المنخفض')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='التصنيف')),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='المزارع')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer', 'is_active'], name='catalog_pro_farmer__52dcf8_idx'), models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'), models.Index(fields=['is_featured', 'is_active', '-created_at'], name='catalog_pro_is_feat_d5cfcb_idx')],
            },
        ),
    ]
