# Generated by Django 5.2.3 on 2026-04-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('role', models.CharField(choices=[('farmer', 'مزارع'), ('buyer', 'مشتري'), ('admin', 'مسؤول'), ('driver', 'سائق')], db_index=True, default='buyer', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='موثق')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('otp_secret', models.CharField(blank=True, max_length=128, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'role'], name='accounts_us_phone_d0822e_idx'), models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx')],
            },
        ),
    ]
